name: prasheen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5004555166233331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.014208548003807664
  lightness: 0.27064576325938106
  saturation: 0.7358131331857294
  rhythmicContrast: 0.716608545044437
purpose: []
